services:
  awad_db:
    image: postgres:16
    environment:
      - POSTGRES_DB=awad_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecret
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  postgres_data:
#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     depends_on:
#       - awad_week4_db
#     environment:
#       - DATABASE_URL=postgresql://postgres:supersecret@awad_week4_db:5432/awad_db?schema=public
#     ports:
#       - '3000:3000'
#     restart: on-failure

#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     ports:
#       - '8080:80'
#     restart: on-failure

